services:
  - type: web
    name: face-swap-app
    env: python
    buildCommand: |
      pip install -r requirements.txt
      curl -L -o inswapper_128.onnx https://huggingface.co/ezioruan/inswapper_128.onnx/resolve/main/inswapper_128.onnx
    startCommand: gunicorn app:app
    envVars:
      - key: PORT
        value: 10000